version: '3'

services:
  vectorstore:
    build:
      context: ./vectorstore-service
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  documentparse:
    build:
      context: ./document-parse-service
    depends_on:
      - embedding-service
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: vectorstore
      DB_PORT: 5432
      EMBEDDINGSERVICE_HOST: embedding-service
      EMBEDDINGSERVICE_PORT: 5000
      EMBEDDING_DIMENSION: 384
      LOGPATH: "/logpath"
      IS_TESTMODE: 0
    volumes:
      - ./logpath:/logpath
    command: python write_db.py

  embedding-service:
    build:
      context: ./embedding-service

  chat-service:
    build:
      context: ./chat-service
      args:
        - HG_FILE=${HG_FILE}
        - HG_REPO=${HG_REPO}
    depends_on:
      documentparse:
        condition: service_completed_successfully
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: vectorstore
      DB_PORT: 5432
      EMBEDDINGSERVICE_HOST: embedding-service
      EMBEDDINGSERVICE_PORT: '5000'
      EMBEDDING_DIMENSION: 384
      LOGPATH: "/logpath"
      HG_FILE: ${HG_FILE}
    volumes:
      - ./logpath:/logpath
    ports:
      - "5001:5001"

    
    
